### PR TITLE
various bug fix, and improve progress bars

### PR DESCRIPTION
**Pull request by dominictarr**
made these changes to get it working with patchwork.
the most important change was to progress bars.

now a progress message looks like this:

``` js
{type: 'progress', peerid: <id>, progress: p, total: t, feeds: f, sync: bool}
```
where `feeds` is the number of mutual feeds you are replicating, and `sync` is whether you are already in sync.

### CODE REVIEW

**Comment by pfraze** [comment]
Does the `sync` attribute mean sbot is using continuous replication?

**Comment by dominictarr** [comment]
@pfraze yes. that is on by default. though, currently there is a timeout that disconnects the replication steam. I'm looking for better ways to do this though. it's worked like that for a while now.

**Comment by dominictarr** [comment]
since the last time i rewrote replication, a few months back.

**Comment by pfraze** [comment]
ok cool, pr looks good

**Comment by dominictarr** [comment]
merged into 7.0.0

technically this is a major change since i removed the rpc.progress observable, and now there is only replicate.changes

**Pull request merged**
