### PR TITLE
api updates for the friends plugin

### PR DESCRIPTION
**Pull request by pfraze**
this updates the trust messages to work as discussed in https://github.com/ssbc/phoenix/issues/257
this also adds `.trust()`, `.follow()`, and `.unfollow()` rpc methods to the friends plugin. i decided to move those functions here since phoenix's apis are moving serverside, so it makes more sense to put those functions here than in the phoenix plugin

### CODE REVIEW

**Comment by pfraze** [comment]
@dominictarr ready for review

**Comment by dominictarr** [comment]
:+1:

**Comment by dominictarr** [comment]
okay lets bump major for this.

**Comment by pfraze** [comment]
published `2.0.0`

**Pull request merged**
