### PR TITLE
Allow setting a note for an invite code

### PR DESCRIPTION
**Pull request by clehner**
%UcqW5DcDjD8U9PbYxTnCz9Zl+7HoUTf8usOnRA4uuOA=.sha256

### CODE REVIEW

**Comment by dominictarr** [comment]
sorry I fogot to merge this, just looked at the code, and it should use just one argument (not counting cb) because with two args you can't use from the cli. one argument is easy to translate from optimist options, so the note should be an option `sbot.create invite --uses 5 --note "invite for bob"` for example.

**Comment by clehner** [comment]
two arguments works from the CLI. e.g.

sbot invite.create 50 https://github.com/ssbc/scuttlebot/wiki/Pub-Servers

named arguments are probably better for usability and extensibility though, so i could change this

**Comment by dominictarr** [comment]
I merged, but changed to `--uses N --note "this is bob"`

**Comment by dominictarr** [comment]
merged into 9.8.0

**Comment by clehner** [comment]
thanks!

**Pull request merged**
