### PR TITLE
cross-spawn module fixes spawning npm on windows

### PR DESCRIPTION
**Pull request by av8ta**
On Windows installing sbot plugins was throwing a spawn error. Using the cross-spawn module means I can install plugins as the instructions say on patchbay, like:
sbot plugins.install ssb-links

### CODE REVIEW

**Comment by dominictarr** [comment]
yup looks good

**Comment by dominictarr** [comment]
merged into 9.5.1, thanks!

**Comment by av8ta** [comment]
pretty chuffed to have my first ever pull request accepted to such a game changing project! thanks :)

**Comment by dominictarr** [comment]
you are welcome! I'm pretty chuffed so many people are excited about it all of a sudden!

**Comment by av8ta** [comment]
I would have been on patchwork a year ago when I first went to art hack if I hadn't been such a node noob at the time and trying to build on windows. Had no idea there were releases I could download until @mmckegg pointed them out - so if it's alright with you guys I'd like to make some pull requests to the readme files from the perspective of a newbie to the scene to make it easier for people to onboard themselves.

**Comment by ahdinosaur** [comment]
> so if it's alright with you guys I'd like to make some pull requests to the readme files from the perspective of a newbie to the scene to make it easier for people to onboard themselves.

please do! :heart_eyes_cat:

**Comment by dominictarr** [comment]
I don't think we _had_ a windows build then!

**Comment by av8ta** [comment]
Ah, so releases are a patchwork-next thing. Sweet - that makes me feel better :)

**Pull request closed without merging**
