### PR TITLE
consolidate current prs into one pr

### PR DESCRIPTION
**Pull request by dominictarr**
this combines https://github.com/ssbc/scuttlebot/pull/158 https://github.com/ssbc/scuttlebot/pull/142 and https://github.com/ssbc/scuttlebot/pull/118

tests pass. I think this should be a breaking change because of https://github.com/ssbc/scuttlebot/pull/158 (breaking change in ssb-msg-schemas)

### CODE REVIEW

**Comment by pfraze** [comment]
actually I dont think sbot uses `ssb-msg-schemas`

**Comment by dominictarr** [comment]
oh, it's in `test/friends.js` moving it into devDeps

**Comment by dominictarr** [comment]
okay so lets just make this a minor

**Comment by pfraze** [comment]
ok looks good

**Comment by dominictarr** [comment]
merged into 4.1.0

**Pull request merged**
