### PR TITLE
replicate peers on the local network, even if they are strangers

### PR DESCRIPTION
**Pull request by dominictarr**
This _should_ replicate strangers you find on the local network, but only the their first 100 messages (by currently hardcoded quotas - easy to change) also it should replicate their avatars.

@mixmix you are more likely to have two computers running pw next to each other, can you test this?

### CODE REVIEW

**Comment by pfraze** [comment]
@dominictarr I tested this on my local machine and got it working, after some fixes. Check the commits to see what I changed. Somethings to mention:

 - For some reason, `cat()` did not appear to successfully add the local peers unless I moved the `pull.values` before the `createFriendStream`. Something is weird about that.
 - I found duplicates from `createFriendStream`, not just the local peers, so I modified the comment to reflect that

This PR is important for enspiral retreat so I'm going to get the tests passing and merge it

**Comment by pfraze** [comment]
published `7.5.1`

**Comment by mixmix** [comment]
Sorry i didn't see this earlier. Sounds good. Exciting!

**Comment by dominictarr** [comment]
@pfraze oh I know, it's because createFriendStream is live and so it doesn't end (to handle case where you learn about a new peer when you replicate a follow message)

**Comment by pfraze** [comment]
@dominictarr ah good

**Pull request merged**
