### PR TITLE
default port 2000 -> 8008

### PR DESCRIPTION
**Pull request by ralphtheninja**
Part of https://github.com/ssbc/phoenix/issues/306

### CODE REVIEW

**Comment by pfraze** [comment]
:+1: you rock man, will review in depth soon

**Comment by pfraze** [comment]
Why close?

**Comment by ralphtheninja** [comment]
Ugh, this was done automatically when I pushed a branch. Not intentionally.

**Comment by pfraze** [comment]
Oh, weird. I can't restore, can you?

**Comment by ralphtheninja** [comment]
I fucked up my master :) No sweat, new PR coming in 3 2 1 ..

**Comment by pfraze** [comment]
https://github.com/ssbc/scuttlebot/pull/118

**Pull request closed without merging**
