### PR TITLE
relatedMessages: remove leftovers

### LINKED ISSUE #518: relatedMessages still handled
This method was removed in ssb@18 but There is still a wrapper for that call and some api docs that should be removed.

See: http://viewer.scuttlebot.io/%25aXka56%2BSBANy6iKejn2cqZ%2Bgbyz5mc3HatFNGg5oBR8%3D.sha256

### PR DESCRIPTION
**Pull request by cryptix**
this call was removed in secure-scuttlebutt v18.

fixes #518

### CODE REVIEW

**Comment by cryptix** [comment]
I'm not so sure if/how many blank lines are required in the `api.md` but otherwise this looks self explanatory to me and the tests still pass.

**Comment by arj03** [comment]
Looks good, there is also cleaning up http://scuttlebot.io/apis/scuttlebot/ssb.html which is probably just as important.

**Comment by cryptix** [comment]
Right! Do you know which repo that is? It’s not ssbc.github.io and not the handbook...

**Comment by dominictarr** [comment]
@cryptix thanks! merged into 11.4.2

**Comment by arj03** [comment]
@cryptix that should be https://github.com/ssbc/scuttlebot.io I think.

**Comment by cryptix** [comment]
Yup. right. Thanks!

I just need to figure out what to do with https://scuttlebot.io/docs/advanced/post-threads.html

I guess links2 is the best api for that? I'll make a new thread for that question.

**Pull request merged**
