### PR TITLE
Init empty feed when starting server

### PR DESCRIPTION
**Pull request by clehner**
This should cause a server with an empty feed (e.g. newly created keypair) to publish an init message when it starts serving. This would address ssbc/phoenix#367 by ensuring that pub servers have profiles, and that their createdAt timestamp will be the time at which the server first started serving.

### CODE REVIEW

**Comment by pfraze** [comment]
Im cool with this, @dominictarr you have any objection?

**Comment by clehner** [comment]
Not ready to merge yet... I need to test this more.

**Comment by dominictarr** [comment]
init messages are no longer used. maybe this is still useful though, but should this be in scuttlebot or phoenix/patchwork?

**Comment by pfraze** [comment]
Patchwork has a UI flow for setting name and profile picture on first load. Maybe we do something similar for pub nodes in the CLI? Theyll need to do both.

**Pull request closed without merging**
