### PR TITLE
Bring package-lock.json up-to-date

### PR DESCRIPTION
**Pull request by christianbundy**
It looks like this has fallen quite a bit behind, so it's hard to tell which packages should _actually_ be getting installed to get everything working. _Keeping_ this file up-to-date will depend on future PRs, but this is a one-time fix to bring us up-to-date.

### CODE REVIEW

**Comment by mmckegg** [comment]
Or just delete it. 😆 

I am not a fan of `package-lock.json`.

Does anyone know of an article about the recommended practice around package-lock.json files? The only case I can think of where they make sense is deploying to a remote server. In app development, they are just a pain. Oh especially when some people are running old versions of npm that don't support them.

**Comment by christianbundy** [comment]
https://docs.npmjs.com/files/package-lock.json

In lieu of an article, here's an example scenario:
1. We specify dependency foo@1.0.x.
2. Others depend on our package.
3. Foo accidentally pushes a breaking change to 1.0.1.
4. Every package that depends on ours is broken.

Lockfiles are a snapshot of the most recent working dependency tree, and they're _incredibly_ useful for issues like this: https://github.com/ssbc/scuttlebot/issues/451#issuecomment-346308695

We can (and probably should) specify which versions of Node and NPM work best with scuttlebot, and as long as you're using NPM to manage `package.json` you shouldn't have to make any workflow changes to keep the lockfile up-to-date.

**Comment by mmckegg** [comment]
How often should a lock file be committed? Every time it changes?

What causes a lock file to update? Sorry I'm from the past 😆 and am still running npm v3. And I am scared of change. (and googling things)

Sorry about my tone above. I am genuinely interested in how lock files work.

**Comment by christianbundy** [comment]
> How often should a lock file be committed? Every time it changes?

Yep, it's just like any other repo file. 

> What causes a lock file to update?

Running `npm install` after a manual change to `package.json`, `npm install --save`, or `npm update` should all do the trick.

> Sorry I'm from the past 😆 and am still running npm v3. And I am scared of change. (and googling things)

It was pretty hairy for a while, but _finally_ the lockfile is working as it should. Don't blame you for wanting to stay on a [more] stable version of NPM!

> Sorry about my tone above. I am genuinely interested in how lock files work.

No tone at all, amigo -- I'm usually the one chanting "delete it" any time a file starts causing trouble. 😉

**Pull request merged**
