### PR TITLE
tracking: refactor gossip, with long term connections

### PR DESCRIPTION
**Pull request by dominictarr**
This introduces long term connections, which should solve battery usage from two much network connections.

A `gossip.ping` stream is added, which keeps a connection alive, (and also measures clock skew and round trip time). an sbot will now connect to up to 3 peers which support long term connections.
sbot will still connect to legacy peers, but only every 5 minutes, on start, sbot attempts a connection to every peer (so they can learn which are running, and which support long term)

currently, my pub is the only one running that supports long term connections.

nearly ready to merge.
TODO: disconnect some peers if they you have more than 3 long term connections.

### CODE REVIEW

**Comment by dominictarr** [comment]
Okay this is now ready for more testing, can people running pubs @pfraze @mixmix @cryptix @bcomnes  update to this branch, and npm install?

This will have pubs rely on long lived connections, but still support legacy style. This should reduce bandwidth and batter usage, and probably improve latency, and also, pave the way for future improvements.

**Comment by bcomnes** [comment]
Nice work! Will update tomorrow.  Time for 🛏

**Comment by bcomnes** [comment]
```
.................................................. 0/1:68ok 1 counter is as expected
ok 2 should be equal
************************************************** 1/1:68ok 3 (unnamed assert)
not ok 4 last.total
  ---
    operator: equal
    expected: 1446
    actual:   1
    at: Timeout._onTimeout (/home/bret/repos/scuttlebot/test/random.js:188:17)
  ...
not ok 5 last.total
  ---
    operator: equal
    expected: 1446
    actual:   1
    at: Timeout._onTimeout (/home/bret/repos/scuttlebot/test/random.js:189:17)
  ...
DONE 467.431 1 3.0935047097860435
************************************************** 1/1:68-disconnected localhost:45451:@gQtwqtez0JKUa7d/TjtfzQOYnl2+2wH8mnJ2oxVwQi8=.ed25519
.................................................. 0/0:68Connect longterm localhost:45451:@gQtwqtez0JKUa7d/TjtfzQOYnl2+2wH8mnJ2oxVwQi8=.ed25519
Connect longterm localhost:45451:@gQtwqtez0JKUa7d/TjtfzQOYnl2+2wH8mnJ2oxVwQi8=.ed25519
Connect longterm localhost:45451:@gQtwqtez0JKUa7d/TjtfzQOYnl2+2wH8mnJ2oxVwQi8=.ed25519

1..5
# tests 5
# pass  3
# fail  2
```

Is it possible to make it so the tests don't run on npm install?  I'll look at extending timeouts again.

**Comment by mixmix** [comment]
Mine is running a -g install... I hit trouble the other way. Will give it a
whirl though

**Comment by bcomnes** [comment]
Opened https://github.com/ssbc/scuttlebot/pull/337 to fix timeout problems on a raspi2.

**Comment by bcomnes** [comment]
Program crashed immediately running behind NAT:
```
/home/bret/.npm-global/bin/sbot server --host pi.bret.io
```

I floated https://github.com/ssbc/secret-stack/pull/6 onto `node_modules/secret-stack` and it started back up.  

Patchwork seems to be syncing fine. 

screenshot 2016-04-03 13 49 22

**Comment by bcomnes** [comment]
Seems to run a lot lighter:
screenshot 2016-04-03 13 57 49

I'll try disabling the nightly restart to see how bad memory leaks.

**Comment by bcomnes** [comment]
Seeing a lot of crashes:

```
Apr 03 18:46:40 bret-raspi systemd[1]: scuttlebot.service: Main process exited, code=exited, status=1/FAILURE
Apr 03 18:46:40 bret-raspi systemd[1]: scuttlebot.service: Unit entered failed state.
Apr 03 18:46:40 bret-raspi systemd[1]: scuttlebot.service: Failed with result 'exit-code'.
Apr 03 18:46:40 bret-raspi systemd[1]: scuttlebot.service: Service hold-off time over, scheduling restart.
Apr 03 18:46:40 bret-raspi systemd[1]: Stopped scuttlebot.
Apr 03 18:46:40 bret-raspi systemd[1]: Started scuttlebot.
Apr 03 18:48:59 bret-raspi systemd[1]: scuttlebot.service: Main process exited, code=exited, status=1/FAILURE
Apr 03 18:48:59 bret-raspi systemd[1]: scuttlebot.service: Unit entered failed state.
Apr 03 18:48:59 bret-raspi systemd[1]: scuttlebot.service: Failed with result 'exit-code'.
Apr 03 18:48:59 bret-raspi systemd[1]: scuttlebot.service: Service hold-off time over, scheduling restart.
Apr 03 18:48:59 bret-raspi systemd[1]: Stopped scuttlebot.
Apr 03 18:48:59 bret-raspi systemd[1]: Started scuttlebot.
Apr 03 18:49:22 bret-raspi systemd[1]: scuttlebot.service: Main process exited, code=exited, status=1/FAILURE
Apr 03 18:49:22 bret-raspi systemd[1]: scuttlebot.service: Unit entered failed state.
Apr 03 18:49:22 bret-raspi systemd[1]: scuttlebot.service: Failed with result 'exit-code'.
Apr 03 18:49:22 bret-raspi systemd[1]: scuttlebot.service: Service hold-off time over, scheduling restart.
Apr 03 18:49:22 bret-raspi systemd[1]: Stopped scuttlebot.
Apr 03 18:49:22 bret-raspi systemd[1]: Started scuttlebot.
Apr 03 18:53:44 bret-raspi systemd[1]: scuttlebot.service: Main process exited, code=exited, status=1/FAILURE
Apr 03 18:53:44 bret-raspi systemd[1]: scuttlebot.service: Unit entered failed state.
Apr 03 18:53:44 bret-raspi systemd[1]: scuttlebot.service: Failed with result 'exit-code'.
Apr 03 18:53:44 bret-raspi systemd[1]: scuttlebot.service: Service hold-off time over, scheduling restart.
Apr 03 18:53:44 bret-raspi systemd[1]: Stopped scuttlebot.
Apr 03 18:53:44 bret-raspi systemd[1]: Started scuttlebot.
Apr 03 18:56:22 bret-raspi systemd[1]: scuttlebot.service: Main process exited, code=exited, status=1/FAILURE
Apr 03 18:56:22 bret-raspi systemd[1]: scuttlebot.service: Unit entered failed state.
Apr 03 18:56:22 bret-raspi systemd[1]: scuttlebot.service: Failed with result 'exit-code'.
Apr 03 18:56:22 bret-raspi systemd[1]: scuttlebot.service: Service hold-off time over, scheduling restart.
Apr 03 18:56:22 bret-raspi systemd[1]: Stopped scuttlebot.
Apr 03 18:56:22 bret-raspi systemd[1]: Started scuttlebot.
Apr 03 19:01:37 bret-raspi systemd[1]: scuttlebot.service: Main process exited, code=exited, status=1/FAILURE
Apr 03 19:01:37 bret-raspi systemd[1]: scuttlebot.service: Unit entered failed state.
Apr 03 19:01:37 bret-raspi systemd[1]: scuttlebot.service: Failed with result 'exit-code'.
Apr 03 19:01:37 bret-raspi systemd[1]: scuttlebot.service: Service hold-off time over, scheduling restart.
Apr 03 19:01:37 bret-raspi systemd[1]: Stopped scuttlebot.
Apr 03 19:01:37 bret-raspi systemd[1]: Started scuttlebot.
```

Turning on logging to see what happens around the crash

**Comment by bcomnes** [comment]
Here is the fatal error

```
Apr 03 21:18:50 bret-raspi systemd[1]: Started scuttlebot.
Apr 03 21:19:09 bret-raspi sbot[1533]: (node) warning: possible EventEmitter memory leak detected. 11 edge listeners added. Use emitter.setMaxListeners() to increase limit.
Apr 03 21:19:09 bret-raspi sbot[1533]: Trace
Apr 03 21:19:09 bret-raspi sbot[1533]:     at Graphmitter.addListener (events.js:252:17)
Apr 03 21:19:09 bret-raspi sbot[1533]:     at Graphmitter.exports.traverse (/home/bret/repos/scuttlebot/node_modules/graphmitter/algorithms.js:85:8)
Apr 03 21:19:09 bret-raspi sbot[1533]:     at Object.<anonymous> (/home/bret/repos/scuttlebot/plugins/friends.js:117:22)
Apr 03 21:19:09 bret-raspi sbot[1533]:     at apply (/home/bret/repos/scuttlebot/node_modules/muxrpc-validation/index.js:171:15)
Apr 03 21:19:09 bret-raspi sbot[1533]:     at Object.<anonymous> (/home/bret/repos/scuttlebot/node_modules/muxrpc-validation/index.js:95:14)
Apr 03 21:19:09 bret-raspi sbot[1533]:     at Object.hooked [as createFriendStream] (/home/bret/repos/scuttlebot/node_modules/hoox/index.js:10:15)
Apr 03 21:19:09 bret-raspi sbot[1533]:     at replicate (/home/bret/repos/scuttlebot/plugins/replicate.js:107:35)
Apr 03 21:19:09 bret-raspi sbot[1533]:     at EventEmitter.<anonymous> (/home/bret/repos/scuttlebot/plugins/replicate.js:222:7)
Apr 03 21:19:09 bret-raspi sbot[1533]:     at emitTwo (events.js:105:20)
Apr 03 21:19:09 bret-raspi sbot[1533]:     at EventEmitter.emit (events.js:185:7)
Apr 03 21:19:10 bret-raspi sbot[1533]: /home/bret/repos/scuttlebot/node_modules/pull-handshake/node_modules/pull-reader/index.js:105
Apr 03 21:19:10 bret-raspi sbot[1533]:             return read.abort(abort, cb)
Apr 03 21:19:10 bret-raspi sbot[1533]:                         ^
Apr 03 21:19:10 bret-raspi sbot[1533]: TypeError: read.abort is not a function
Apr 03 21:19:10 bret-raspi sbot[1533]:     at /home/bret/repos/scuttlebot/node_modules/pull-handshake/node_modules/pull-reader/index.js:105:25
Apr 03 21:19:10 bret-raspi sbot[1533]:     at Function.reader.abort (/home/bret/repos/scuttlebot/node_modules/pull-reader/index.js:65:7)
Apr 03 21:19:10 bret-raspi sbot[1533]:     at /home/bret/repos/scuttlebot/node_modules/pull-box-stream/index.js:107:29
Apr 03 21:19:10 bret-raspi sbot[1533]:     at Function.reader.abort (/home/bret/repos/scuttlebot/node_modules/pull-reader/index.js:65:7)
Apr 03 21:19:10 bret-raspi sbot[1533]:     at /home/bret/repos/scuttlebot/node_modules/packet-stream-codec/index.js:96:31
Apr 03 21:19:10 bret-raspi sbot[1533]:     at next (/home/bret/repos/scuttlebot/node_modules/pull-stream/throughs.js:111:9)
Apr 03 21:19:10 bret-raspi sbot[1533]:     at /home/bret/repos/scuttlebot/node_modules/muxrpc/pull-weird.js:24:15
Apr 03 21:19:10 bret-raspi sbot[1533]:     at /home/bret/repos/scuttlebot/node_modules/muxrpc/pull-weird.js:10:5
Apr 03 21:19:10 bret-raspi sbot[1533]:     at PacketStream.weird.read (/home/bret/repos/scuttlebot/node_modules/muxrpc/pull-weird.js:37:15)
Apr 03 21:19:10 bret-raspi sbot[1533]:     at PacketStream._maybedone (/home/bret/repos/scuttlebot/node_modules/packet-stream/index.js:98:8)
Apr 03 21:19:10 bret-raspi systemd[1]: scuttlebot.service: Main process exited, code=exited, status=1/FAILURE
Apr 03 21:19:10 bret-raspi systemd[1]: scuttlebot.service: Unit entered failed state.
Apr 03 21:19:10 bret-raspi systemd[1]: scuttlebot.service: Failed with result 'exit-code'.
Apr 03 21:19:10 bret-raspi systemd[1]: scuttlebot.service: Service hold-off time over, scheduling restart.
Apr 03 21:19:10 bret-raspi systemd[1]: Stopped scuttlebot.
```

**Comment by dominictarr** [comment]
@bcomnes weird that it should crash every few minutes on your server but not on my laptop. Do you think this is a big enough problem not to merge?

**Comment by pfraze** [comment]
@dominictarr I'll give it a run on my pub tomorrow. If we're lucky, I'll get the same crash and I can try debugging it.

**Comment by dominictarr** [comment]
@pfraze it turned out it was really simple, when I actually looked at the code. will merge this in a sec.

**Comment by pfraze** [comment]
that's good to hear

**Comment by dominictarr** [comment]
oh, yeah, this made some breaking changes to the gossip api, so this will break the sync page.

```
// what does patchwork use?

// .time.connect
// .time.attempt (to count how many pubs you are on)
// .host (to check if this is is on the lan - instead use .source===local)
// .announcers (for sorting; change to sorting by last connect)
// .key (to check if this peer follows you) 
// .connected (to see if currently connected)
```

`time.* ` becomes `stateChange` and the `state` is your current state. This is much simpler because you the most important thing is how long you have been in the current state.
announcers becomes a counter, not an array.
instead of `connected` use `state === 'connected'`

This doesn't effect pubs, I'll make a PR to update patchwork.

**Comment by dominictarr** [comment]
merged into 8.0.0
the breaking changes do not effect pubs, go ahead and upgrade pubs.
the network sync screen doesn't _error_ but it is non-functional.

**Comment by bcomnes** [comment]
Woo!  Been running for like 9 hours without a crash... memory usage still appears unbounded:

screen shot 2016-04-08 at 3 45 39 pm

**Comment by pfraze** [comment]
That may be, in part, from a leveldown issue that's getting fixed: https://github.com/Level/leveldown/issues/272#issuecomment-207167377

**Comment by mixmix** [comment]
Awesome, will deploy to pub mix. I was running this branch earlier and it
didn't seem to be giving any troubles

**Pull request merged**
