### PR TITLE
merge all the flume stuff! (also add blocking)

### PR DESCRIPTION
**Pull request by dominictarr**
This is all ready now, y'all!

this merges all the flume stuff, as well as adds blocking. The replication policy is all shifted out into ssb-friends, so that is easy to change. It's also possible to replicate someone non persistently, so you could replicate someone when you open their profile, but without following them - their feed would not be replicated next time you start ssb.

to block someone:

``` js
sbot publish --type contact --contact <feed_id> --blocking
```

I just gotta update ssb-ebt to some of the new ideas in here, but this is all ready to merge!

**important**: when you start this after using old scuttlebot it will migrate from the old database to a flume one, which will take a while. if you want to check the progress, use `sbot.since` and that will dump the state of all the views, when the numbers stop changing, your are ready.

### CODE REVIEW

**Comment by mmckegg** [comment]
@dominictarr Continuing on from [my thoughts about merging this into patchwork](https://github.com/ssbc/patchwork/pull/539#issuecomment-305053803):

Is there some way the query/links plugins can detect that the indexes are legacy and regenerate? Or use a different prefix or something? Because if this was in place, no user intervention would be needed to upgrade from legacy to flume sbots. Or if it used a different prefix, you'd be able to switch back again without making a big mess.

**Also, a question:** Does flume store all of its data inside `~/.ssb/flume` and ignore `~/.ssb/db` or is `db` still used for something? How does the "convert" work (if there is one)? Or am I misunderstanding what flume is?

**Comment by mmckegg** [comment]
Okay, upon further investigation it appears I was wrong.

Looks like scuttlebot@10 + plugins are fully compatible with older versions (no need to delete things from your `~/.ssb/`). Just takes ages to reindex. So, I guess all that patchwork needs is a progress bar and then everything would be perfect 😄

**Comment by dangerousbeans** [comment]
Am getting test failure here on commit 74e50ad

```
/javascript/scuttlebot/test/block2.js:48
      if(once) throw new Error('should only be called once')
               ^

Error: should only be called once
    at Array.<anonymous> (/javascript/scuttlebot/test/block2.js:48:22)
```

**Comment by dangerousbeans** [comment]
All good with `node v7.5.0` on macOS, migrating from old scuttlebutt with a bunch of database

**Comment by mmckegg** [comment]
A stream ticking down with the number of pending messages would be fine (maybe it could debounce to 200ms like the replication one).

Did you see my comments about progress [here](https://github.com/ssbc/patchwork/pull/539#issuecomment-305054343)? 

It only took about 1 minute for the patchwork feed to appear, so not too bad really. Probably most people would have just waited with the spinners going but I assumed that it was broken (being a common failure mode in patchwork right now)!

**Comment by dangerousbeans** [comment]
Trying a new technique by copying across my `private` file to a new folder created by `ssb_appname=flume sbot server --allowPrivate`

This is replicating from Helena's (current SSB) laptop on the WIFI but my flume sbot keeps flunking out at:

 ```
/Users/joran/Documents/development/javascript/scuttlebot/node_modules/aligned-block-file/blocks.js:0



RangeError: Maximum call stack size exceeded
    at Function.isBuffer (buffer.js:282:12)
    at get (/Users/joran/Documents/development/javascript/scuttlebot/node_modules/aligned-block-file/blocks.js:24:15)
    at Object.readUInt32BE (/Users/joran/Documents/development/javascript/scuttlebot/node_modules/aligned-block-file/blocks.js:88:9)
    at /Users/joran/Documents/development/javascript/scuttlebot/node_modules/flumelog-offset/frame/recoverable.js:33:16
    at /Users/joran/Documents/development/javascript/scuttlebot/node_modules/aligned-block-file/blocks.js:91:11
    at get (/Users/joran/Documents/development/javascript/scuttlebot/node_modules/aligned-block-file/blocks.js:25:7)
    at Object.readUInt32BE (/Users/joran/Documents/development/javascript/scuttlebot/node_modules/aligned-block-file/blocks.js:88:9)
    at getMeta (/Users/joran/Documents/development/javascript/scuttlebot/node_modules/flumelog-offset/frame/recoverable.js:23:12)
    at next (/Users/joran/Documents/development/javascript/scuttlebot/node_modules/pull-cursor/cursor.js:27:11)
    at /Users/joran/Documents/development/javascript/scuttlebot/node_modules/pull-cursor/cursor.js:20:11
```

**Comment by dominictarr** [comment]
@dangerousbeans sorry, pull the latest.

Yes, should fix that error. though, that is something you can just restart a few times and it will work... I don't have any test coverage for the migration script, but we can make some...

**Comment by dangerousbeans** [comment]
Cannot boot it now at d42610e

```
Log level: notice
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8989
    at Object.exports._errnoException (util.js:1023:11)
    at exports._exceptionWithHostPort (util.js:1046:20)
    at Server._listen2 (net.js:1261:14)
    at listen (net.js:1297:10)
    at Server.listen (net.js:1375:9)
    at Object.exports.init (/Users/joran/.ssb/node_modules/ssb-ws/index.js:67:49)
    at /Users/joran/Documents/development/javascript/scuttlebot/node_modules/secret-stack/api.js:27:28
    at Array.forEach (native)
    at create (/Users/joran/Documents/development/javascript/scuttlebot/node_modules/secret-stack/api.js:26:20)
    at Object.<anonymous> (/Users/joran/Documents/development/javascript/scuttlebot/bin.js:59:16)
```

**Comment by dangerousbeans** [comment]
cleared `.ssb/node_modules`
and removed the following config:

```
{
  "plugins": {
    "ssb-links": true,
    "ssb-query": true,
    "ssb-ws": true,
    "ssb-blobs": true,
    "ssb-search": true,
    "ssb-fulltext": false,
    "patchfoo": false,
    "ssb-notifier": true
  },
  "allowPrivate": true,
  "allowRemoteAccess": false,
  "ws": {
    "port": 8989
  }
}
```

now boots again :D

**Comment by dangerousbeans** [comment]
Published a message from Helena's laptop with my flume in sync, got this almost right away:

```
Disconnected diasp.club:8008:@DNatJUQOFr1NZewA3oRG9i/r0XJZLbKYTyB225J9St0=.ed25519
/Users/joran/Documents/development/javascript/scuttlebot/node_modules/multiblob/index.js:184
        else if(opts.max != null && opts.max < stat.size)
                                                   ^

TypeError: Cannot read property 'size' of undefined
    at /Users/joran/Documents/development/javascript/scuttlebot/node_modules/multiblob/index.js:184:52
    at done (/Users/joran/Documents/development/javascript/scuttlebot/node_modules/multiblob/index.js:41:38)
    at FSReqWrap.oncomplete (fs.js:112:15)
```

No new messages still, even from local, but stuff is going out

**Comment by evbogue** [comment]
This is working on http://github.com/evbogue/minbase -- ready to merge into master on my end.

**Comment by arj03** [comment]
I has the same problem as @dangerousbeans

**Comment by evbogue** [comment]
no problems here, getting new messages. I'm not sure why, but I've also been using flume for awhile so that might be it.

**Comment by evbogue** [comment]
@arj03 Are you getting `Error: listen EADDRINUSE :::8989` ? Because that's a result of two `ssb-ws` plugins loading at the same time.

**Comment by arj03** [comment]
After installing the plugins I'm getting these errors:

NotFoundError: could not find matching timestamp for index:{"value":{"content":{"channel":"ssb-show-and-tell"}},"timestamp":1496392047964}
    at /home/chrx/.ssb/node_modules/ssb-query/node_modules/streamview-links/index.js:164:31
    at /home/chrx/.ssb/node_modules/ssb-query/index.js:67:26
  NotFoundError: missing timestamp:1496392047964
    at /home/chrx/.ssb/node_modules/ssb-query/index.js:67:29
    at /home/chrx/dev/scuttlebot/node_modules/secure-scuttlebutt/node_modules/level-sublevel/shell.js:101:15
  NotFoundError: Key not found in database
    at /home/chrx/dev/scuttlebot/node_modules/secure-scuttlebutt/node_modules/level-sublevel/shell.js:101:18
    at /home/chrx/dev/scuttlebot/node_modules/secure-scuttlebutt/node_modules/level-sublevel/nut.js:121:19

Also had one when navigating to #flume

The indexes seems to have been updated. At least it doesn't update the x and . in terminal any longer.

**Comment by clehner** [comment]
When updating to this version from v9, ssb-links, ssb-query, and ssb-ws 
should be removed from the plugins config object, since scuttlebot now will 
load them directly in bin.js. Should this be noted somewhere? Or should 
scuttlebot/plugins/plugins.js detect and skip these specifically for this 
case (with a warning logged)?

**Comment by dominictarr** [comment]
@clehner good point. Maybe it should just refuse to load another plugin with the same name? that would do it.

**Comment by dominictarr** [comment]
@arj03 the problem you are seeing there is that ssb-query uses stream-viewlinks, but flume was all about taking that _idea_ and making it the main thing - so we can just remove ssb-query now.

**Comment by arj03** [comment]
Ok, but then it should probably refuse to load it?

**Comment by dominictarr** [comment]
merged https://github.com/ssbc/scuttlebot/pull/411 into this PR, gonna merge this thing!

**Comment by mmckegg** [comment]
I just noticed that we are not using the latest legacy replication code. It's fallen back to the old one before we fixed the double pull stream hack that I did for progress sync back in the day.

We should be using this: https://github.com/ssbc/scuttlebot/blob/ea4748e7991a1f992b96faf319cbfd5059639a03/plugins/replicate.js

**Comment by mmckegg** [comment]
@dominictarr need to merge latest replication code here: https://github.com/ssbc/scuttlebot/pull/412

**Comment by dangerousbeans** [comment]
not sure if right place, but am getting **plugin at:ssb-links expected name:links but had:links2**

```
/Users/joran/Documents/development/javascript/scuttlebot/plugins/plugins.js:187
        throw new Error('plugin at:'+module_name+' expected name:'+name+' but had:'+plugin.name)
        ^

Error: plugin at:ssb-links expected name:links but had:links2
    at Object.module.exports.loadUserPlugins (/Users/joran/Documents/development/javascript/scuttlebot/plugins/plugins.js:187:15)
    at Object.<anonymous> (/Users/joran/Documents/development/javascript/scuttlebot/bin.js:54:32)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
FAIL: 1
```

**Comment by arj03** [comment]
@dangerousbeans as far as I know its because ssb-links is not needed anymore and can be safely deleted.

**Comment by dominictarr** [comment]
@dangerousbeans just remove the `"ssb-links": true` line from the `plugins` section of your `~/.ssb/config`

**Comment by dangerousbeans** [comment]
FIXED thanks

**Pull request merged**
