### PR TITLE
Fixed test timeout for raspi2

### PR DESCRIPTION
**Pull request by bcomnes**
Test was timing out on raspi2's.

### CODE REVIEW

**Comment by pfraze** [comment]
@dominictarr merge?

**Comment by bcomnes** [comment]
Just a reminder, this is a pr to an outstanding pr.

**Comment by bcomnes** [comment]
But yeah, okay to merge.  I can't tell if it was or not, but it looks like it was?

**Comment by dominictarr** [comment]
oh, sorry. I will merge this.

**Comment by bcomnes** [comment]
Doesn't seem to be an issue right now. Closing

**Pull request closed without merging**
