### PR TITLE
add time measurement to replication summary notice-log

### PR DESCRIPTION
**Pull request by pfraze**
Adds some time information so we can get an idea of the throughput:

```
note @pzI REPL @uRECWB4KIeKoNMis2UYWyB2aQPvWmS3OePQvBj2zClg=.ed25519 success
  "Feeds updated: 20, New messages: 28, in 0m31s"
```

### CODE REVIEW

**Comment by dominictarr** [comment]
hmm, this might not represent total throughput because the connection will stay open for 30 seconds of inactivity, so the time of the connection doesn't necessarily show the total rate... it would be better to have progress events output a messages/second and then display that somewhere.

**Comment by pfraze** [comment]
Yeah we could definitely do something better. Do you think it's worth the time? This is still somewhat useful

**Comment by dominictarr** [comment]
yes I think performance monitoring is definitely a good thing, but it will take some iterations to get good.

**Comment by pfraze** [comment]
@dominictarr ok, merge or close, up to you

**Pull request closed without merging**
