### PR TITLE
fix friends graph creation (use .sync event)

### PR DESCRIPTION
**Pull request by pfraze**
fixes https://github.com/ssbc/scuttlebot/issues/138

@dominictarr if you'd prefer to keep using level-memview, I can move this fix into that repo. This code is pretty compact, though.

### CODE REVIEW

**Comment by pfraze** [comment]
@dominictarr good to merge this?

**Comment by dominictarr** [comment]
yeah this is good

**Comment by dominictarr** [comment]
lets merge

**Comment by pfraze** [comment]
will lump this with #171

**Comment by pfraze** [comment]
published `4.2.3`

**Pull request merged**
