### PR TITLE
Handle IPv6 addresses

### PR DESCRIPTION
**Pull request by clehner**
This patch updates scuttlebot to correctly parse addresses with IPv6 hostnames, as in
https://github.com/ssbc/ssb-ref/commit/3e68d06149e19847e8bcb6ea8975c9227ca555c5 and
https://github.com/ssbc/ssb-ref/commit/8d5f7c3badc8e5fc48090e384d8fa5458619a0f7

### CODE REVIEW

**Comment by pfraze** [comment]
Ok good deal. Could you add a test-case for this in test/invite.js? I think you could overwrite the server's getAddress to return an IPv6.

**Comment by clehner** [comment]
Added a test which should fail before 5232100 and pass after it

**Comment by clehner** [comment]
CI test failed at `replicate social network for animals`. Re-run it?

**Comment by pfraze** [comment]
There might be a race in that test. Restarted...

**Comment by pfraze** [comment]
Tests passing. @dominictarr good to merge?

**Comment by dominictarr** [comment]
merged into 7.4.6

**Comment by dominictarr** [comment]
sorrf 7.4.7

**Pull request merged**
