### PR TITLE
tracking PR to add encrypted channels

### PR DESCRIPTION
**Pull request by dominictarr**
This is a tracking pull request to add point-to-point encryption via secret-handshake.
>note, this pull request is made on top of the replication perf PR.

so far I have test/server.js passing.

There is quite a simplification that can happen here, for example, since secret-handshake
handles mutual authentication we can remove all the auth stuff.

### CODE REVIEW

**Comment by dominictarr** [comment]
okay this also rewrites the cap code. special cases like hmac auth are gone.
to mint a cap, generate a private key from a seed, and share your `ip:port,publicKey,seed`
saving permissions you will give them.
then using cap-client a peer may login (fixed number of times) and use the api you have restricted them to.

TODO: refactor the create cap system out of the invite plugin and make it generic.

**Comment by dominictarr** [comment]
this is now passing all the tests at my end.

**Comment by dominictarr** [comment]
todo for after this
* rethink browser logon, possibly with secret-handshake working in the browser?
* kill emit permission. it's used to track when tasks are done, and in blobs.
* better muxrpc encoding... so that buffers do not need to be base64 encoded.

**Comment by pfraze** [comment]
Looking great so far! Got some questions

 1. What's the purpose of `client.js` versus `ssb-client`, do we just need to merge those?
 2. What was the method for producing the ssb protocol cap?

**Comment by dominictarr** [comment]
@pfraze I added a comment explaining it: https://github.com/dominictarr/scuttlebot/commit/24e86c06f8660a0ce91f477d7c892e9f6cd846ba

**Comment by pfraze** [comment]
cool, what about client.js?

**Comment by dominictarr** [comment]
oh yeah, that functionality should be moved to ssb-client

**Comment by dominictarr** [comment]
Okay this will currently not be working with phoenix, but I think we have enough here to merge a major version.
I'll work on ssb-client next.

**Comment by dominictarr** [comment]
oops, I still need to rewrite invites! no merge yet.

**Comment by dominictarr** [comment]
Okay, turns out invites was easy! Aliased `invite.accept` to `invite.addMe` I don't know why I didn't think of that sooner...

**Comment by dominictarr** [comment]
removed `done` event... and tests still passed. blobs are the only events left now

**Comment by dominictarr** [comment]
(rpc events, i mean)

**Comment by dominictarr** [comment]
permissions for the emit method are now gone. instead i wrote https://github.com/dominictarr/pull-notify 
allows an event emitter of pull streams.
(see also: https://github.com/ssbc/muxrpc/issues/23)

**Comment by pfraze** [comment]
:+1: :confetti_ball: lots of great stuff in this one

**Pull request merged**
