### PR TITLE
Updates to support a sync-progress UI in phoenix

### PR DESCRIPTION
**Pull request by pfraze**
These changes will make it possible to implement the "initial sync" ui, and a general network-sync UI, in phoenix.

### CODE REVIEW

**Comment by pfraze** [comment]
@dominictarr it would be awesome if we could show a progress bar with % complete in phoenix, especially for the initial sync.

We'd need to know how many messages we're downloading. To get that we either need to modify `createHistoryStream` to send that data, or we need to add an extra RPC call to the remote. Could do the extra call in parallel - if the response doesnt come before replication ends, no biggy.

**Comment by dominictarr** [comment]
@pfraze actually we do know that because _they_ send their `createHistoryStream` so you know what they are up to, we just have to intercept the incoming `createHistoryStream` arguments.

**Comment by dominictarr** [comment]
hmm, i started working on getting progress out of a replication stream... and I found something very weird.
If I gave pull-paramap a width parameter (https://github.com/ssbc/secure-scuttlebutt/blob/master/index.js#L326-L331) (asking it to only make that many in flight requests at once...) then things worked, else they went weird. If there is no width parameter, paramap makes requests as fast as it can.

This gives me a hunch about maybe somethings sometimes took too long... too many concurrent requests to the database? there are several other uses of paramap without widths (maybe solution is to set a default width?)

**Comment by dominictarr** [comment]
:+1:

**Comment by pfraze** [comment]
published `5.2.0`

**Pull request merged**
