### PR TITLE
Progress3

### PR DESCRIPTION
**Pull request by dominictarr**
this should ensure that a progress event is emited once we are in sync.

### CODE REVIEW

**Comment by pfraze** [comment]
:+1:

**Comment by pfraze** [comment]
@dominictarr Can you update the progress events to include the hostname and port of the peer? Key is not 100% uniquely identifiable

**Comment by dominictarr** [comment]
@pfraze it ought to be. when you receive connections it will come from a random outgoing port, so it won't really be useful. I suggest we just use the key.

**Comment by pfraze** [comment]
@dominictarr This condition is currently visible, your pub has an announcement for localhost and for its public id:

```
176.58.117.63:8008:@J+0DGLgRn8H5tVLCcRUfN7NfUcTGEZKqML3krEOJjDY=.ed25519
localhost:8008:@J+0DGLgRn8H5tVLCcRUfN7NfUcTGEZKqML3krEOJjDY=.ed25519
```

**Comment by dominictarr** [comment]
@pfraze yes. people can publish invalid pubs, so we should filter that out. better: just use the key, and swap that for a name if available.

**Comment by pfraze** [comment]
@dominictarr It's hard to evaluate which pub declarations are invalid. What if a pub is announced under two public IPs? Do we filter out based on failed connects? What if the net was just down, or what if the server is moving and the new address was announced before the move?

**Comment by dominictarr** [comment]
@pfraze yes, you have to try and if it fails remove it. I guess you could flag pubs as well. but they would have to be presented in the UI in some way.

**Comment by pfraze** [comment]
Yeah I think this will need to be a UI concern

**Comment by pfraze** [comment]
published `7.2.8`

**Pull request merged**
