### PR TITLE
trigger gossip syncs when the device wakes up from sleep

### PR DESCRIPTION
**Pull request by pfraze**
#245

### CODE REVIEW

**Comment by pfraze** [comment]
@dominictarr ready for review

**Comment by dominictarr** [comment]
It's only ten lines, but what do you think about putting this in a separate module?
it would be a short module, but signs that it would work:

* it would do what it says on the tin (called "on-wakeup" or something)
* it's internal workings arn't relavant to anything else in scuttlebot
* it's interface is simple (takes a callback + timeout)

Also, you can use `interval.unref()` and that interval won't keep the process alive, so you don't need to close that (node only)

**Comment by pfraze** [comment]
Ah, sure

**Comment by pfraze** [comment]
@dominictarr ok done!

**Comment by dominictarr** [comment]
looks great!

**Comment by dominictarr** [comment]
merged into 7.3.3

**Pull request merged**
