### PR TITLE
Expose log command in logging plugin

### PR DESCRIPTION
**Pull request by clehner**
This makes the log function from the logging plugin be usable as a method/command. This makes it possible for ssb apps connecting to scuttlebot using ssb-client to log messages to the same output to which sbot's log messages go.

Also I added an API doc for the log function and updated an isString function to be more accepting of strings

### CODE REVIEW

**Comment by pfraze** [comment]
Is this a good idea? Shouldnt apps have their own logs?

**Comment by clehner** [comment]
> Shouldnt apps have their own logs?

Maybe so. I wanted to reuse the functionality of logging with levels. An app running as a plugin would have access to the server's log. There isn't a feature-checking way to check if that log is available though because it is done as event listeners, which is why I added the log method.

However, if scuttlebot logging is meant to be internal to scuttlebot, an app can still get the logging level from the config, and the levels functionality is simple enough, so this isn't a big need.

**Comment by clehner** [comment]
Wouldn't centralizing the logs allow for fixing the problem of the new gossip logging not being configurable? (mentioned on GH or PW, I forgot)

**Comment by pfraze** [comment]
No, that's just happening because the latest logging code is using console.log() instead of emitting log messages

**Pull request closed without merging**
