### PR TITLE
mention Node in the install

### PR DESCRIPTION
**Pull request by mixmix**

### CODE REVIEW

**Comment by ahdinosaur** [comment]
nvm link is broken, maybe link to <https://github.com/creationix/nvm#node-version-manager->?

**Comment by pfraze** [comment]
why not link to https://nodejs.org/ ?

**Comment by mixmix** [comment]
their install gives you a tar.gz file and no help :(

you can change it to nodejs if you like. I think mentioning that it's a node project to someone who's quite new would be a kindness though

**Comment by dominictarr** [comment]
yes this is good - we need to grow this beyond the node community

**Comment by pfraze** [comment]
done int he docs

**Pull request closed without merging**
