### PR TITLE
Blobsmerge

### PR DESCRIPTION
**Pull request by dominictarr**
I added my changes, but something is holding the test blob test you added open.
(I moved it into `test/blobs3.js`, since the blob tests had a tendency to take ages at it was easier if you could run them separately)

### CODE REVIEW

**Comment by pfraze** [comment]
@dominictarr just a heads up, to `npm install secret-handshake` I had to `brew install automake libtool`

**Comment by dominictarr** [comment]
@pfraze oh, I must have had that already... we can set up prebuilt binaries like leveldown uses now.

**Comment by dominictarr** [comment]
then it will work easily on windows etc

**Comment by pfraze** [comment]
Aha, found the bug: no `key` on the seed address for replication

**Pull request merged**
