### PR TITLE
enable configuring no gossip, or connect to seeds only

### PR DESCRIPTION
**Pull request by dominictarr**
@pietgeursen needed this, so I cherry-picked it from the flume branch.

### CODE REVIEW

**Comment by dominictarr** [comment]
merged into 9.7.0, 
oh btw, this makes it possible to actually turn off different types of gossip.

``` js
"gossip": {
  "local": false, //do not replicate peers on the local network
  "global": false, //do not replicate with peers on the internet
  "seeds": false, //do not replicate with seeds.
},
//seeds to connect to my pub, and cel's pub.
"seeds": [
    "net:104.236.22.57:8008~shs:5XaVcAJ5DklwuuIkjGz4lwm2rOnMHHovhNg7BFFnyJ8=",
    "net:128.199.132.182:8008~shs:DTNmX+4SjsgZ7xyDh5xxmNtFqa6pWi5Qtw7cE8aR9TQ="
  ],
```

seeds are optional, but have been useful for developing ebt.

**Comment by arj03** [comment]
Nice, would be good to add that comment to the docs.

**Comment by kseistrup** [comment]
Is there a way to ban sbot from connecting to certain hostnames and/or IP addresses?

I run sbot with `--allowPrivate` because I want to include the fc00::/8 address space, and it seems sbot picks up, e.g., `localhost:9000` via gossip. Can I tell sbot to ignore that without being overly broad?

**Comment by dominictarr** [comment]
@kseistrup right so you want to connect to cjdns but not the regular internet? localhost:9000 is really a separate problem - there are some badly formed pub announcements which say localhost, and they should just be ignored

**Comment by kseistrup** [comment]
@dominictarr No, I want sbot to connect to the regular internet (IPv4 and IPv4) _and_ any fc00::/8 addresses it might have heard of, and I want it to ignore localhost:9000 (mostly because it spams my syslog, but also because it's a waste of time).

**Comment by dominictarr** [comment]
got it. hmm, probably it should just ignore localhost unless it's provided as a seed (this is used in the tests)
This isn't a configuration problem though, it's a code problem.

**Comment by kseistrup** [comment]
I agree about ignoring localhost.

Still, couldn't it be useful to have a way to ban/mute/keelhaul individual nodes?

**Comment by dominictarr** [comment]
@kseistrup sure, I would gladly merge PRs for either or both!

**Comment by kseistrup** [comment]
I'd be more than happy to. Alas, I don't speak js.

**Comment by dominictarr** [comment]
@kseistrup the changes you are talking about wouldn't be very complicated, if you can do any programming language you could probably figure it out, we'd be happy to help guide you, but given that there is a huge bredth of things that need doing, trying and asking for help would make it happen a lot faster than waiting for someone else to get around to it.

**Comment by kseistrup** [comment]
@dominictarr Thanks for the advice and optimism, I'll see what I can do.

**Pull request merged**
