### PR TITLE
get everything working with Sha256

### PR DESCRIPTION
**Pull request by dominictarr**
okay! this is it!

### CODE REVIEW

**Comment by pfraze** [comment]
:+1:

**Comment by ralphtheninja** [comment]
Why are you switching?

**Comment by dominictarr** [comment]
@ralphtheninja changing all the crypto to C implementations, for speed.

This made a tremendus difference with signatures, since asymetric crypto is in general much more expensive that symmetric*, but switching to JS hashes made generating a large dataset (https://github.com/ssbc/ssb-testnet) 30% faster. Sodium does have a blake2b,
but i needed to make a PR to the bindings, and it wouldn't be compatible with blake2s anyway.

(*here i did some simple perf tests learn the relative costs of the various primitives: https://github.com/dominictarr/sodiumperf)

**Comment by dominictarr** [comment]
anything needed before we merge?

**Comment by pfraze** [comment]
dont think so, Ive been working with this branch for a bit

**Comment by dominictarr** [comment]
am merging this.

**Pull request merged**
