### PR TITLE
add trust and flag edges to friend graphs

### PR DESCRIPTION
**Pull request by pfraze**
modifies the friend plugin functions to optionally take the desired graph

```js
server.friends.all('follow')
server.friends.all() // same as ^
server.friends.all('trust')
server.friends.all('flag')

server.friends.hops(alice, 'follow')
server.friends.hops(alice, 'trust')
server.friends.hops(alice, 'flag')
```

also adds edge-deletion to the graph construction

### CODE REVIEW

**Comment by pfraze** [comment]
published `1.2.1`

**Comment by dominictarr** [comment]
it would be better to have the graphs in an object and then just pick one off than to have the `if...else`

``` js
var graphs = {
  trust: new Graphmitter(),
  follow: new Graphmitter(),
  flag: new Graphmitter()
}

//and then. etc
if(!Object.hasOwnProperty(graphs, type))
  throw new Error('no graph'))
return graphs[type].toJSON()
```

It does the same thing, but is much more terse, and has less edge cases, because it doesn't support the plugal version. There is no benefit to having multilpe names to the same thing unless we are supporting a legacy pattern that hasn't been completely cleaned up yet.

**Comment by pfraze** [comment]
ok :+1:

**Comment by pfraze** [comment]
we're going to need to re-approach this per https://github.com/ssbc/phoenix/issues/257

**Pull request merged**
