### PR TITLE
Emit gossip log messages rather than logging to console

### PR DESCRIPTION
**Pull request by amsross**
Use `server.emit('log:info', ['SBOT', xyz, 'Xxz'])`, rather than `console.log('Xxz', xyz)` for the gossip plugin's sometimes chatty information updates.

### CODE REVIEW

**Comment by mmckegg** [comment]
Now included in [Patchwork](https://github.com/ssbc/patchwork)!

**Comment by staltz** [comment]
Good PR. I just wonder what should be done to get Travis tests passing? See this https://travis-ci.org/ssbc/scuttlebot/builds/285602139#L1312

**Comment by amsross** [comment]
The [build history](https://travis-ci.org/ssbc/scuttlebot/builds) is kind of back and forth about the failures if you go back to before about 5 months ago. More recently than that, it's all failures. Based on the types of changes those statuses tie to, it kind of looks like successes and failures happen arbitrarily. The linked failure, for instance, has been present in `master` for months.

As a casual user/investigator, I'm not close enough to the test approach or the underlying behavioral expectations to guess what is _actually_ failing here.

**Comment by amsross** [comment]
If it's of any use, I opened an issue related to this: https://github.com/ssbc/scuttlebot/issues/447

**Comment by arj03** [comment]
Thanks! Don't know why this stalled, but seems like everyone agrees that its good.

**Pull request merged**
