### PR TITLE
Tracking PR: command-line rewrite to use muxrpcli

### PR DESCRIPTION
**Pull request by pfraze**
Two goals: 1. factor out `muxrpcli`, and 2. provide better live help

### CODE REVIEW

**Comment by dominictarr** [comment]
this is good but (as discussed on irc) there is some room for improvement around the usage convention.
we discussed yaml and (a strict) markdown format

**Comment by pfraze** [comment]
@dominictarr ok what do you think of the `usage()` pattern now?

Things still todo:

 - need to update plugins to work with this
 - do we want to read the markdown files using `fs` at runtime? would we prefer to use `require()` so that noderify can put the markdown in the js bundle?
 - there are some weirdities to handle in the manifest: getAddress, getLocal, maybe others, were in the manifest (in `./index.js`) but not exported
 - we need docs for auth and query, @dominictarr I'm passing those to you

**Comment by pfraze** [comment]
that covers all the docs except `query` and `auth`

**Comment by ahdinosaur** [comment]
:+1: woot @pfraze :smile: (will try to expand on my use case once i have capacity, cheers for this though)

**Comment by pfraze** [comment]
@ahdinosaur you bet! Dont know if you saw, but this will solve our CLI help issue too (via https://github.com/ssbc/mdmanifest)

**Comment by ahdinosaur** [comment]
yes, really happy with the approach you've taken, separating out the cli interface (which points to the possibility of more interface modules: http, websockets, zmq, whatever) and using markdown as both docs and manifests.

**Comment by pfraze** [comment]
:+1: :rainbow:

**Comment by pfraze** [comment]
question: would it be better to put all api docs in one file, and then share that (and its output manifest) with the plugins?

**Comment by ahdinosaur** [comment]
`¯\_(ツ)_/¯`

splitting it up seems reasonable as well.

**Comment by dominictarr** [comment]
i guess calling it "plugins" implies that we are at least hoping to refactor them out at some point, so leaving them separate is probably better!

**Comment by pfraze** [comment]
> there are some weirdities to handle in the manifest: getAddress, getLocal, maybe others, were in the manifest (in ./index.js) but not exported

Tests pass without, I dont know of any code that depends on them. Going to assume that was cruft that needed removing

**Comment by pfraze** [comment]
Going to bump patch because this only adds docs and input validation, it doesn't add behaviors.

**Comment by pfraze** [comment]
published `7.2.3`

**Pull request merged**
