### PR TITLE
hack: override blobs.add CLI call, in bin.js, to get the hash output

### PR DESCRIPTION
**Pull request by pfraze**
@dominictarr we discussed this previously. This will make `sbot blobs.add` output the hash of the added file.

### CODE REVIEW

**Comment by pfraze** [comment]
Solves https://github.com/ssbc/scuttlebot/issues/284

**Comment by pfraze** [comment]
Merged master into this branch, which included the tests fix so tests are now passing

**Comment by dominictarr** [comment]
oh i just realized that the bit that used to do this in publish got obliterated with muxrpcli

**Comment by dominictarr** [comment]
https://github.com/ssbc/scuttlebot/blob/7260b52d03cf865e06e6673c7f865fdf93e2e4d4/bin.js#L181-L221

**Comment by dominictarr** [comment]
is that more useful? then you can post a message with attachments via one command.
or is this just so that documentation is consistent? maybe what we ought to do is provide a thing that wraps the client and does this so that ssb-client can be consistent too.

**Comment by pfraze** [comment]
> is that more useful?

Both seem useful to me. I like having blobs.add output the hash for me. So if we also want to do this I'd be down.

> maybe what we ought to do is provide a thing that wraps the client and does this so that ssb-client can be consistent too.

that might be a good idea, instead of in sbot here

**Comment by dominictarr** [comment]
what about... if a value is a file (source stream) `blobs.add` that instead, and replace that stream with a link. for the cli, we'd check if that arg is a file (or `.` for stdin)

**Comment by dominictarr** [comment]
merged this into 7.5.0 for now anyway.

**Pull request merged**
