### PR TITLE
Tracking: implement blocking.

### PR DESCRIPTION
**Pull request by dominictarr**
have also refactored auth api to simplify integration.
currently blocked clients are prevented from connecting (to the blocker)
next is update to replication plugin to prevent blocked requesting blocker's data.

### CODE REVIEW

**Comment by pfraze** [comment]
:+1: looks good

**Comment by dominictarr** [comment]
still a bit more work to do here. tests are failing because this depends on the latest secure-scuttlebutt but we havn't merged that pr yet

**Comment by dominictarr** [comment]
this is now fully functional, but just needs to be refactored so that it's not so tightly coupled.

**Comment by dominictarr** [comment]
refactoring is taking a bit longer than i intendend, so i think we should just merge this, and then it won't be stalling anything.

**Comment by pfraze** [comment]
Go ahead if you want to, but Im actually blocked until the link changes land, so it doesnt matter too much whether this PR merges. (Not 100% blocked, fwiw.)

**Comment by dominictarr** [comment]
which link changes?

**Comment by pfraze** [comment]
The sigils and message structure changes

**Comment by dominictarr** [comment]
right, okay cool

**Pull request merged**
